// <auto-generated>
// 自动生成的存档代码，请勿手动修改
// </auto-generated>

using UnityEngine;
using System.Collections.Generic;
using System;

namespace GameData
{
    public partial class PlayerData
    {
        [System.Serializable]
        public class ArchiveData
        {
            public int _version = 2;
            public int Level;
            public int exp;
            public int GemCount;
            public Vector3 LastPosition;
        }

        public ArchiveData Archive()
        {
            var data = new ArchiveData();
            data.Level = this.Level;
            data.exp = this._experience;
            data.GemCount = EncryptValue(this.GemCount);
            data.LastPosition = this.LastPosition;
            return data;
        }

        public void Restore(ArchiveData data)
        {
            if (data == null) return;
            
            // 版本检查与迁移
            if (data._version < 2)
            {
                MigrateFromOldVersion(data);
            }

            this.Level = (data.Level);
            this._experience = (data.exp != null ? data.exp : 0);
            this.GemCount = (DecryptValue<Int32>(data.GemCount));
            this.LastPosition = (data.LastPosition);
            OnRestored?.Invoke();
        }

        public void ResetToDefault()
        {
            this._experience = (0);
        }

        public System.Action OnRestored;

        partial void MigrateFromOldVersion(ArchiveData data);

        private T EncryptValue<T>(T value) => value; // 接入你的加密系统
        private T DecryptValue<T>(object value) => (T)value;
    }
}
