// Editor/ArchiveCodeGenerator.cs
using UnityEngine;
using UnityEditor;
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Reflection;

public static class ArchiveCodeGenerator 
{
    private const string OUTPUT_PATH = "Assets/Custom/Archive/";
    
    [MenuItem("Tools/Archive/Generate All Savable Classes")]
    public static void GenerateAll()
    {
        if (!Directory.Exists(OUTPUT_PATH))
            Directory.CreateDirectory(OUTPUT_PATH);

        int generatedCount = 0;
        
        // 扫描所有程序集
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            foreach (var type in assembly.GetTypes())
            {
                if (type.GetCustomAttribute<AutoArchiveAttribute>() != null && !type.IsAbstract)
                {
                    GenerateForType(type);
                    generatedCount++;
                }
            }
        }
        
        AssetDatabase.Refresh();
        Debug.Log($"[ArchiveGenerator] 生成完成: {generatedCount} 个类");
    }

    private static void GenerateForType(Type dataType)
    {
        var className = dataType.Name;
        var nameSpace = dataType.Namespace ?? "GameData";
        var fullName = $"{nameSpace}.{className}";
        
        // 收集所有标记[Savable]的成员
        var members = new List<MemberInfo>();
        members.AddRange(dataType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance));
        members.AddRange(dataType.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance));
        
        var savableMembers = new List<(MemberInfo member, SavableAttribute attr, string key, string typeName)>();
        
        foreach (var member in members)
        {
            var attr = member.GetCustomAttribute<SavableAttribute>();
            if (attr == null) continue;
            
            string key = string.IsNullOrEmpty(attr.Key) ? member.Name : attr.Key;
            string typeName = GetTypeName(member);
            
            savableMembers.Add((member, attr, key, typeName));
        }

        if (savableMembers.Count == 0) return;

        // 构建代码
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 自动生成的存档代码，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine($"using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {nameSpace}");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine($"    {{");
        
        // 生成存档数据结构
        sb.AppendLine($"        [System.Serializable]");
        sb.AppendLine($"        public class ArchiveData");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            public int _version = {dataType.GetCustomAttribute<AutoArchiveAttribute>().Version};");
        
        foreach (var item in savableMembers)
        {
            string fieldType = item.member is FieldInfo fi 
                ? GetSerializableTypeName(fi.FieldType) 
                : GetSerializableTypeName(((PropertyInfo)item.member).PropertyType);
            
            sb.AppendLine($"            public {fieldType} {item.key};");
        }
        sb.AppendLine($"        }}");
        sb.AppendLine();

        // Archive() 方法
        sb.AppendLine($"        public ArchiveData Archive()");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            var data = new ArchiveData();");
        
        foreach (var item in savableMembers)
        {
            string accessCode = GetMemberAccessCode(item.member, "this");
            if (item.attr.Encrypt)
            {
                sb.AppendLine($"            data.{item.key} = EncryptValue({accessCode});");
            }
            else
            {
                sb.AppendLine($"            data.{item.key} = {accessCode};");
            }
        }
        sb.AppendLine($"            return data;");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        // Restore() 方法
        sb.AppendLine($"        public void Restore(ArchiveData data)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            if (data == null) return;");
        sb.AppendLine($"            ");
        sb.AppendLine($"            // 版本检查与迁移");
        sb.AppendLine($"            if (data._version < {dataType.GetCustomAttribute<AutoArchiveAttribute>().Version})");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                MigrateFromOldVersion(data);");
        sb.AppendLine($"            }}");
        sb.AppendLine();
        
        foreach (var item in savableMembers)
        {
            string setCode = GetMemberSetCode(item.member, "this");
            string valueCode = item.attr.Encrypt 
                ? $"DecryptValue<{item.typeName}>(data.{item.key})" 
                : $"data.{item.key}";
            
            // 处理默认值
            if (item.attr.DefaultValue != null && !IsNumeric(item.typeName))
            {
                sb.AppendLine($"            {setCode}(data.{item.key} != null ? {valueCode} : {FormatDefaultValue(item.attr.DefaultValue)});");
            }
            else
            {
                sb.AppendLine($"            {setCode}({valueCode});");
            }
        }
        sb.AppendLine($"            OnRestored?.Invoke();");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        // 重置方法
        sb.AppendLine($"        public void ResetToDefault()");
        sb.AppendLine($"        {{");
        foreach (var item in savableMembers)
        {
            if (item.attr.DefaultValue != null)
            {
                string setCode = GetMemberSetCode(item.member, "this");
                sb.AppendLine($"            {setCode}({FormatDefaultValue(item.attr.DefaultValue)});");
            }
        }
        sb.AppendLine($"        }}");
        sb.AppendLine();

        // 事件与回调
        sb.AppendLine($"        public System.Action OnRestored;");
        sb.AppendLine();
        
        // 迁移虚方法
        sb.AppendLine($"        partial void MigrateFromOldVersion(ArchiveData data);");
        
        // 加密辅助（如果用到）
        bool hasEncryption = savableMembers.Exists(x => x.attr.Encrypt);
        if (hasEncryption)
        {
            sb.AppendLine();
            sb.AppendLine($"        private T EncryptValue<T>(T value) => value; // 接入你的加密系统");
            sb.AppendLine($"        private T DecryptValue<T>(object value) => (T)value;");
        }

        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");

        // 写入文件
        string fileName = $"{className}.Archive.gen.cs";
        File.WriteAllText(Path.Combine(OUTPUT_PATH, fileName), sb.ToString());
    }

    // 辅助方法：获取成员访问代码
    private static string GetMemberAccessCode(MemberInfo member, string instance)
    {
        if (member is FieldInfo)
            return $"{instance}.{member.Name}";
        else
            return $"{instance}.{member.Name}";
    }

    private static string GetMemberSetCode(MemberInfo member, string instance)
    {
        if (member is FieldInfo)
            return $"{instance}.{member.Name} = ";
        else
            return $"{instance}.{member.Name} = ";
    }

    private static string GetTypeName(MemberInfo member)
    {
        Type type = member is FieldInfo fi ? fi.FieldType : ((PropertyInfo)member).PropertyType;
        return type.Name;
    }

    private static string GetSerializableTypeName(Type type)
    {
        if (type == typeof(int)) return "int";
        if (type == typeof(float)) return "float";
        if (type == typeof(string)) return "string";
        if (type == typeof(bool)) return "bool";
        if (type == typeof(Vector2)) return "Vector2";
        if (type == typeof(Vector2Int)) return "Vector2Int";
        if (type == typeof(Vector3)) return "Vector3";
        if (type == typeof(Vector3Int)) return "Vector3Int";
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
            return $"List<{GetSerializableTypeName(type.GetGenericArguments()[0])}>";
        if (type.IsArray)
            return $"{GetSerializableTypeName(type.GetElementType())}[]";
        // 字典
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<,>))
            return $"Dictionary<{GetSerializableTypeName(type.GetGenericArguments()[0])}, {GetSerializableTypeName(type.GetGenericArguments()[1])}>";

        // throw new NotSupportedException($"不支持的类型：{type.FullName}");
        return type.FullName;
    }
    private static bool IsNumeric(string type)
    {
        // return type == typeof(int) || type == typeof(float) || type == typeof(double) || type == typeof(decimal);
        return type == "int" || type == "float" || type == "double" || type == "decimal";
    }

    private static string FormatDefaultValue(object value)
    {
        if (value is string s) return $"\"{s}\"";
        if (value is bool b) return b.ToString().ToLower();
        return value.ToString();
    }
}